name: Release and Publish

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    uses: Orbitary/Convention/.github/workflows/publish.yml@main
    with:
      modules: ""
      gradleGroup: "xyz.orbitary.notion"
    secrets: inherit